yaml_file_path: "data/label-color-map.yaml"

train_path: "data/raw/train"
pcd_files_path: "data/raw/train/pcd"
asc_files_path: "data/raw/train/asc"
test_path: "data/test"
val_path: "data/val"

preprocessed_data_dir: "data/preprocessed"
preprocessed_train_dir: "data/preprocessed/train"
preprocessed_val_dir: "data/preprocessed/val"
preprocessed_test_dir: "data/preprocessed/test"
model_save_path: "data/model"

train_ratio: 0.7
val_ratio: 0.15
test_ratio: 0.15
shuffle: True
random_seed: null

batch_size: 1
lr: 0.001
step_size: 30
momentum: 0.9
gamma: 0.1
log_interval: 10
weight_decay: 0.0001
num_epochs: 1000
voxel_size: 0.01
alpha: 0.5
stride: 1

num_classes: 25

num_workers: 24
num_gpus: 1
